package kanta.test;
// Generated by ComTest BEGIN
import kanta.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.22 21:40:28 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AineTarkistusTest {



  // Generated by ComTest BEGIN
  /** testTarkista18 */
  @Test
  public void testTarkista18() {    // AineTarkistus: 18
    AineTarkistus aineet = new AineTarkistus(); 
    assertEquals("From: AineTarkistus line: 21", "lisää ainesosa!", aineet.tarkista("")); 
    assertEquals("From: AineTarkistus line: 22", "Täytyy lisätä määrä", aineet.tarkista("2dl maitoa,jauhoja")); 
    assertEquals("From: AineTarkistus line: 23", null, aineet.tarkista("50g voita,200g keksejä")); 
  } // Generated by ComTest END
}