package leivonta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import leivonta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.26 11:12:20 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AllergiaTest {



  // Generated by ComTest BEGIN
  /** testParse58 */
  @Test
  public void testParse58() {    // Allergia: 58
    Allergia allergia = new Allergia(); 
    allergia.parse("1|pähkinätön, munaton|"); 
    assertEquals("From: Allergia line: 61", 1, allergia.getTunnusNro()); 
    assertEquals("From: Allergia line: 62", "1|pähkinätön, munaton", allergia.toString()); 
    allergia.rekisteroi(); 
    int n = allergia.getTunnusNro(); 
    allergia.parse(""+(n+20)); 
    allergia.rekisteroi(); 
    assertEquals("From: Allergia line: 68", n+20+1, allergia.getTunnusNro()); 
    assertEquals("From: Allergia line: 69", "" + (n+20+1) + "|pähkinätön, munaton", allergia.toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString93 */
  @Test
  public void testToString93() {    // Allergia: 93
    Allergia allergia = new Allergia(); 
    allergia.parse ("1|pähkinätön, munaton|"); 
    assertEquals("From: Allergia line: 96", "1|pähkinätön, munaton", allergia.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi126 */
  @Test
  public void testRekisteroi126() {    // Allergia: 126
    Allergia pahkinaton = new Allergia(); 
    assertEquals("From: Allergia line: 128", 0, pahkinaton.getTunnusNro()); 
    pahkinaton.rekisteroi(); 
    Allergia munaton = new Allergia(); 
    munaton.rekisteroi(); 
    int n1 = pahkinaton.getTunnusNro(); 
    int n2 = munaton.getTunnusNro(); 
    assertEquals("From: Allergia line: 134", n2-1, n1); 
  } // Generated by ComTest END
}