package leivonta.test;
// Generated by ComTest BEGIN
import java.io.File;
import leivonta.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.26 11:12:20 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AllergiatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta51 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta51() throws SailoException {    // Allergiat: 51
    Allergiat allergiat = new Allergiat(); 
    Allergia al1 = new Allergia(); al1.vastaaPahkinaton(); 
    Allergia al2 = new Allergia(); al2.vastaaPahkinaton(); 
    Allergia al3 = new Allergia(); al3.vastaaPahkinaton(); 
    String tiedNimi = "testileivonta"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    allergiat.lueTiedostosta(tiedNimi); 
    fail("Allergiat: 61 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    allergiat.lisaa(al1); 
    allergiat.lisaa(al2); 
    allergiat.lisaa(al3); 
    allergiat.tallenna(); 
    allergiat = new Allergiat(); 
    allergiat.lueTiedostosta(tiedNimi); 
    Iterator<Allergia> i = allergiat.iterator(); 
    assertEquals("From: Allergiat line: 69", al1.toString(), i.next().toString()); 
    assertEquals("From: Allergiat line: 70", al2.toString(), i.next().toString()); 
    assertEquals("From: Allergiat line: 71", al3.toString(), i.next().toString()); 
    assertEquals("From: Allergiat line: 72", false, i.hasNext()); 
    allergiat.lisaa(al1); 
    allergiat.tallenna(); 
    assertEquals("From: Allergiat line: 75", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Allergiat line: 77", true, fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator177 */
  @Test
  public void testIterator177() {    // Allergiat: 177
    Allergiat allergiat = new Allergiat(); 
    Allergia pahkinaton = new Allergia(); allergiat.lisaa(pahkinaton); 
    Allergia pahkinaton2 = new Allergia(); allergiat.lisaa(pahkinaton2); 
    Allergia munaton = new Allergia(); allergiat.lisaa(munaton); 
    Iterator<Allergia> i2 = allergiat.iterator(); 
    assertEquals("From: Allergiat line: 187", pahkinaton, i2.next()); 
    assertEquals("From: Allergiat line: 188", pahkinaton2, i2.next()); 
    assertEquals("From: Allergiat line: 189", munaton, i2.next()); 
    try {
    assertEquals("From: Allergiat line: 190", munaton, i2.next()); 
    fail("Allergiat: 190 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}