package leivonta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import leivonta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.26 11:12:20 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class OhjeTest {



  // Generated by ComTest BEGIN
  /** testClone57 */
  @Test
  public void testClone57() {    // Ohje: 57
    Ohje oh = new Ohje(); 
    oh.parse("1|1|1|Perinteinen|200g keksejä, 75g voita...|1. Sulata voi ja murskaa keksit...|120"); 
    assertEquals("From: Ohje line: 60", "1", oh.anna(0)); 
    assertEquals("From: Ohje line: 61", "1", oh.anna(1)); 
    assertEquals("From: Ohje line: 62", "1", oh.anna(2)); 
    assertEquals("From: Ohje line: 63", "Perinteinen", oh.anna(3)); 
    assertEquals("From: Ohje line: 64", "200g keksejä, 75g voita...", oh.anna(4)); 
    assertEquals("From: Ohje line: 65", "1. Sulata voi ja murskaa keksit...", oh.anna(5)); 
    assertEquals("From: Ohje line: 66", "120", oh.anna(6)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse96 */
  @Test
  public void testParse96() {    // Ohje: 96
    Ohje ohje = new Ohje(); 
    ohje.parse("1|1|1|Perinteinen|200g keksejä, 75g voita...|1. Sulata voi ja murskaa keksit...|120"); 
    assertEquals("From: Ohje line: 99", 1, ohje.getReseptiNro()); 
    assertEquals("From: Ohje line: 100", "1|1|1|Perinteinen|200g keksejä, 75g voita...|1. Sulata voi ja murskaa keksit...|120", ohje.toString()); 
    ohje.rekisteroi(); 
    int n = ohje.getTunnusNro(); 
    ohje.parse(""+(n+20)); 
    ohje.rekisteroi(); 
    assertEquals("From: Ohje line: 106", n+20+1, ohje.getTunnusNro()); 
    assertEquals("From: Ohje line: 107", "" + (n+20+1) + "|1|1|Perinteinen|200g keksejä, 75g voita...|1. Sulata voi ja murskaa keksit...|120", ohje.toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna127 */
  @Test
  public void testAnna127() {    // Ohje: 127
    Ohje oh = new Ohje(); 
    oh.parse("1|1|1|Perinteinen|200g keksejä, 75g voita...|1. Sulata voi ja murskaa keksit...|120"); 
    assertEquals("From: Ohje line: 130", "1", oh.anna(0)); 
    assertEquals("From: Ohje line: 131", "1", oh.anna(1)); 
    assertEquals("From: Ohje line: 132", "1", oh.anna(2)); 
    assertEquals("From: Ohje line: 133", "Perinteinen", oh.anna(3)); 
    assertEquals("From: Ohje line: 134", "200g keksejä, 75g voita...", oh.anna(4)); 
    assertEquals("From: Ohje line: 135", "1. Sulata voi ja murskaa keksit...", oh.anna(5)); 
    assertEquals("From: Ohje line: 136", "120", oh.anna(6)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString216 */
  @Test
  public void testToString216() {    // Ohje: 216
    Ohje ohje = new Ohje(); 
    ohje.parse("1|1|1|Perinteinen|200g keksejä, 75g voita...|1. Sulata voi ja murskaa keksit...|120"); 
    assertEquals("From: Ohje line: 219", "1|1|1|Perinteinen|200g keksejä, 75g voita...|1. Sulata voi ja murskaa keksit...|120", ohje.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi271 */
  @Test
  public void testRekisteroi271() {    // Ohje: 271
    Ohje perinteinen = new Ohje(); 
    assertEquals("From: Ohje line: 273", 0, perinteinen.getTunnusNro()); 
    perinteinen.rekisteroi(); 
    Ohje gluteeniton = new Ohje(); 
    gluteeniton.rekisteroi(); 
    int n1 = perinteinen.getTunnusNro(); 
    int n2 = gluteeniton.getTunnusNro(); 
    assertEquals("From: Ohje line: 279", n2-1, n1); 
  } // Generated by ComTest END
}